// ─── Moa's read gate: no prompt for reading the repos it delegated to ─────────
//
// Moa (the HQ terminal brain) checks a worker's result by reading the files it
// changed. Those files sit in another workspace's checkout, outside Moa's home,
// so every read stopped on a permission prompt the operator had to answer.
// This gate answers the safe ones itself, inside a narrow scope:
//
//   - WHICH TOOLS: Read of one file, Grep on one file, Glob in a directory.
//     A Grep over a directory always asks: ripgrep reads every file under it,
//     and secret files with ordinary names or hard links cannot be vetted one
//     by one. Writes, edits and commands keep their deny list or prompt.
//   - WHICH ROOTS: the gate asks MAIN, over its authenticated pipe, for the
//     roots main holds in memory (`deck.moaReadRoots`, its own client lane).
//     There is no roots file: a same-user process (a delegated worker has an
//     unattended shell) could rewrite one. Main's roots are:
//       (a) the `git rev-parse --show-toplevel` of a hand-off's pane, taken
//           once at delivery (a pane's cwd is OSC 7: unverifiable means no
//           root);
//       (b) the worktree of an open fan-out task of the HQ (main made it).
//     Main and the gate both refuse a root that is `/`, $HOME or above it,
//     the wmux data dir or ~/.claude.
//   - NEVER: a `.git` / `.ssh` / `.gnupg` / `.aws` segment, a secret file by
//     name (case-insensitive on every platform: macOS volumes usually are), a
//     hard-linked file, a symlink out of the root (real paths compared), a
//     Glob pattern that could match a secret name.
//   - ANYTHING ELSE, or any error (no pipe, no answer within the timeout): the
//     script prints nothing and exits 0, so Claude Code shows its normal
//     prompt. It never blocks (exit 2) and never allows by default.
//
// Main writes the script beside the brain profile at spawn and rewrites it
// before every turn if its content changed.
//
// Measured on Claude Code 2.1.289 (the PR records the runs): a PreToolUse
// `allow` skips the prompt; no output + exit 0 falls through to it; a
// settings-level `deny` still wins over a hook `allow`.

import { execFile } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { getWmuxDir } from '../../daemon/config';

/** How long a root outlives its task's end while Moa still owns the job. */
export const READ_ROOT_GRACE_MS = 60 * 60_000;
/** How long an open task's root stands before main must re-stamp it. */
export const READ_ROOT_OPEN_TTL_MS = 10 * 60_000;
/** How long the gate waits for main's answer before it asks the operator. */
export const READ_GATE_TIMEOUT_MS = 2_000;

export interface ReadRoot {
  path: string;
  expiresAt: number;
}

/**
 * The generated gate, run as `node read-gate.cjs` for every Read, Grep and
 * Glob of the HQ brain. Self-contained CommonJS: it runs in the brain's
 * process tree, not in main. Every path out that is not an explicit allow
 * ends with no output and exit 0.
 */
export function buildReadGateScript(): string {
  return `// Generated by wmux (moaReadGate.ts). Main writes it at every brain spawn and
// rewrites it before a turn if it changed: edits here are lost.
'use strict';
const fs = require('fs');
const net = require('net');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const WIN = process.platform === 'win32';
const TIMEOUT_MS = ${READ_GATE_TIMEOUT_MS};
const SEGMENTS = new Set(['.git', '.ssh', '.gnupg', '.aws']);
const SECRET_NAMES = [
  /^\\.env(\\..*)?$/i, /\\.(pem|key|p12|pfx|kdbx|keystore|jks|gpg|asc)$/i,
  /^id_(rsa|dsa|ecdsa|ed25519)/i, /^\\.git-credentials$/i, /^\\.pgpass$/i, /^\\.npmrc$/i, /^\\.netrc$/i, /^credentials/i,
];
// A file whose name is only secret under one folder.
const SECRET_PAIRS = [['.docker', 'config.json'], ['gh', 'hosts.yml']];
// Names a Glob pattern must not be able to match (one per secret rule).
const SECRET_SAMPLES = ['.env', '.env.local', 'x.pem', 'x.key', 'x.p12', 'x.pfx', 'x.kdbx', 'x.keystore', 'x.jks', 'x.gpg', 'x.asc',
  'id_rsa', 'id_dsa', 'id_ecdsa', 'id_ed25519', 'id_ed25519.pub', '.git-credentials', '.pgpass', '.npmrc', '.netrc', 'credentials',
  'credentials.json', 'hosts.yml', 'config.json', '.git', '.ssh', '.gnupg', '.aws'];

function suffix() { return process.env.WMUX_DATA_SUFFIX || ''; }
function home() { return process.env.USERPROFILE || process.env.HOME || os.homedir(); }
function norm(p) {
  if (!WIN) return p;
  let s = p;
  if (s.startsWith('\\\\\\\\?\\\\UNC\\\\')) s = '\\\\\\\\' + s.slice(8);
  else if (s.startsWith('\\\\\\\\?\\\\')) s = s.slice(4);
  return s.toLowerCase();
}
function real(p) {
  try { return norm(fs.realpathSync.native(p)); } catch { return null; }
}
function inside(target, root) {
  return target === root || target.startsWith(root.endsWith(path.sep) ? root : root + path.sep);
}
function secretName(name, parent) {
  const base = name.toLowerCase();
  if (SEGMENTS.has(base) || SECRET_NAMES.some((re) => re.test(base))) return true;
  return SECRET_PAIRS.some(([dir, file]) => (parent || '').toLowerCase() === dir && base === file);
}
function secretPath(p) {
  const parts = p.split(/[\\\\/]+/).filter(Boolean);
  if (parts.some((s) => SEGMENTS.has(s.toLowerCase()))) return true;
  return secretName(parts[parts.length - 1] || '', parts[parts.length - 2]);
}
// One glob segment as a case-insensitive regex (*, ?, [..], {a,b}).
function segmentRe(seg) {
  let re = '';
  for (let i = 0; i < seg.length; i++) {
    const c = seg[i];
    if (c === '*') re += '.*';
    else if (c === '?') re += '.';
    else if (c === '{') { const end = seg.indexOf('}', i); if (end < 0) return null; re += '(' + seg.slice(i + 1, end).split(',').map((x) => x.replace(/[.+^$()|\\\\[\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*').replace(/\\?/g, '.')).join('|') + ')'; i = end; }
    else if (c === '[') { const end = seg.indexOf(']', i); if (end < 0) return null; re += seg.slice(i, end + 1); i = end; }
    else re += c.replace(/[.+^$()|\\\\]/g, '\\\\$&');
  }
  try { return new RegExp('^' + re + '$', 'i'); } catch { return null; }
}
function patternMaySeeSecrets(pattern) {
  const segs = pattern.split(/[\\\\/]+/).filter(Boolean);
  for (const seg of segs) {
    if (seg === '**') continue;
    if (seg === '..' ) return true;
    const re = segmentRe(seg);
    if (!re) return true;
    if (SECRET_SAMPLES.some((name) => re.test(name))) return true;
  }
  return false;
}
// Never a root: the filesystem root, $HOME or above it, wmux's data, ~/.claude.
function acceptableRoot(root) {
  const h = real(home());
  if (!h || root === path.parse(root).root || inside(h, root)) return false;
  for (const b of [path.join(home(), '.wmux' + suffix()), path.join(home(), '.claude')]) {
    const rb = real(b);
    if (rb && (inside(root, rb) || inside(rb, root))) return false;
  }
  return true;
}
function pipePath() {
  if (WIN) return '\\\\\\\\.\\\\pipe\\\\wmux' + suffix() + '-' + (os.userInfo().username || 'default');
  return path.join(os.homedir() || '/tmp', '.wmux' + suffix() + '.sock');
}
// Main's roots, or null on any failure.
function askMain() {
  return new Promise((resolve) => {
    let token = null;
    try { token = fs.readFileSync(path.join(home(), '.wmux' + suffix() + '-auth-token'), 'utf8').trim() || null; } catch { token = null; }
    if (!token) return resolve(null);
    const id = 'read-gate-' + crypto.randomUUID();
    let buf = '';
    let done = false;
    const sock = net.createConnection(pipePath());
    const finish = (v) => { if (done) return; done = true; clearTimeout(timer); try { sock.destroy(); } catch { /* gone */ } resolve(v); };
    const timer = setTimeout(() => finish(null), TIMEOUT_MS);
    sock.on('connect', () => sock.write(JSON.stringify({ id, method: 'deck.moaReadRoots', params: {}, token, clientName: 'wmux-read-gate' }) + '\\n'));
    sock.on('data', (d) => {
      buf += d.toString('utf8');
      let nl;
      while ((nl = buf.indexOf('\\n')) >= 0) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        let m;
        try { m = JSON.parse(line); } catch { continue; }
        if (!m || m.id !== id) continue;
        const roots = m.ok === true && m.result && Array.isArray(m.result.roots) ? m.result.roots : null;
        return finish(roots);
      }
    });
    sock.on('error', () => finish(null));
    sock.on('close', () => finish(null));
  });
}
// A target inside a root, as a real path, or null.
function scoped(raw, cwd, roots) {
  if (typeof raw !== 'string' || !raw) return null;
  // The path vetted here must be the one the tool opens. Claude Code trims
  // the path (U+00A0 too), and on Windows ripgrep's Win32 open drops trailing
  // dots and spaces of every part, while realpath (\\\\?\\ form) keeps them:
  // a planted "server.pem " would be vetted as itself and read as server.pem.
  if (raw !== raw.trim()) return null;
  if (WIN && raw.split(/[\\\\/]+/).some((s) => s !== '.' && s !== '..' && /[. ]$/.test(s))) return null;
  const abs = path.isAbsolute(raw) ? raw : (typeof cwd === 'string' ? path.resolve(cwd, raw) : null);
  if (!abs) return null;
  const rp = real(abs);
  if (!rp || secretPath(rp) || secretPath(abs)) return null;
  return roots.some((root) => inside(rp, root)) ? rp : null;
}
function safeFile(rp) {
  const st = fs.statSync(rp);
  return st.isFile() && st.nlink <= 1;
}
function decide(input, roots) {
  const tool = input.tool_name;
  const t = input.tool_input || {};
  if (tool === 'Read') {
    const rp = scoped(t.file_path, null, roots);
    return !!rp && safeFile(rp);
  }
  if (tool === 'Grep') {
    // One file only: a directory search reads files nobody vetted.
    const rp = scoped(t.path, input.cwd, roots);
    return !!rp && safeFile(rp);
  }
  if (tool === 'Glob') {
    const rp = scoped(t.path, input.cwd, roots);
    if (!rp || !fs.statSync(rp).isDirectory()) return false;
    const pattern = t.pattern;
    return typeof pattern === 'string' && !!pattern && !path.isAbsolute(pattern) && !patternMaySeeSecrets(pattern);
  }
  return false;
}
let input = '';
process.stdin.on('data', (d) => { input += d; });
process.stdin.on('end', async () => {
  try {
    const parsed = JSON.parse(input);
    if (['Read', 'Grep', 'Glob'].includes(parsed.tool_name)) {
      const answer = await askMain();
      const roots = (answer || []).filter((r) => typeof r === 'string').map(real).filter((r) => r && acceptableRoot(r));
      if (roots.length > 0 && decide(parsed, roots)) {
        process.stdout.write(JSON.stringify({ hookSpecificOutput: {
          hookEventName: 'PreToolUse',
          permissionDecision: 'allow',
          permissionDecisionReason: 'A read inside a repository Moa delegated work to.',
        } }));
      }
    }
  } catch {
    /* no decision: Claude Code shows its normal prompt */
  }
  process.exit(0);
});
`;
}

/** Main's current roots for the gate (`deck.moaReadRoots`): in memory only. */
let currentRoots: readonly ReadRoot[] = [];
export function setMoaReadRoots(roots: readonly ReadRoot[]): void {
  currentRoots = roots;
}
/** The paths the gate may use now: unexpired and re-vetted. */
export function currentMoaReadRoots(now: number = Date.now(), accept: (p: string) => boolean = (p) => isAcceptableReadRoot(p)): string[] {
  return currentRoots.filter((r) => r.expiresAt > now && accept(r.path)).map((r) => r.path);
}

/**
 * Is this a directory Moa may read freely? Never the filesystem root, the
 * home directory or anything above it, the wmux data dir or ~/.claude (or
 * anything inside those two). Compared as real paths.
 */
export function isAcceptableReadRoot(
  root: string,
  opts: { home?: string; blocked?: readonly string[]; realpath?: (p: string) => string } = {},
): boolean {
  const realpath = opts.realpath ?? ((p: string) => fs.realpathSync.native(p));
  let r: string;
  let home: string;
  try {
    r = realpath(root);
    home = realpath(opts.home ?? os.homedir());
  } catch {
    return false;
  }
  const inside = (a: string, b: string): boolean => a === b || a.startsWith(b.endsWith(path.sep) ? b : b + path.sep);
  if (r === path.parse(r).root) return false;
  if (inside(home, r)) return false; // $HOME itself or an ancestor of it
  for (const b of opts.blocked ?? [getWmuxDir(), path.join(os.homedir(), '.claude')]) {
    let rb: string;
    try {
      rb = realpath(b);
    } catch {
      continue;
    }
    if (inside(r, rb) || inside(rb, r)) return false;
  }
  return true;
}

/** `git rev-parse --show-toplevel` in `cwd`, accepted only when it succeeds
 *  and names an acceptable root (isAcceptableReadRoot). Null otherwise. */
export function resolveRepoRoot(
  cwd: string | undefined,
  opts: { run?: (cwd: string) => Promise<string | null>; accept?: (root: string) => boolean } = {},
): Promise<string | null> {
  if (!cwd || !path.isAbsolute(cwd)) return Promise.resolve(null);
  const run = opts.run ?? ((dir: string) => new Promise<string | null>((resolve) => {
    execFile('git', ['-C', dir, 'rev-parse', '--show-toplevel'], { timeout: 5_000, windowsHide: true }, (err, stdout) => {
      resolve(err ? null : String(stdout).trim() || null);
    });
  }));
  const accept = opts.accept ?? ((root: string) => isAcceptableReadRoot(root));
  return run(cwd).then((root) => (root && path.isAbsolute(root) && accept(root) ? root : null)).catch(() => null);
}

/** What the roots are computed from. */
export interface ReadRootSources {
  now: number;
  /** The setting is on and Moa runs. Off: no roots at all. */
  enabled: boolean;
  /** Hand-offs of the current HQ that carry a captured repo root. */
  handoffs: ReadonlyArray<{
    repoRoot?: string;
    taskId?: string;
    open: boolean;
    /** When the task ended; absent while it is open. */
    endedAt?: number;
    /** wmux ended it because its pane closed: no grace. */
    paneGone?: boolean;
  }>;
  /** Task ids the HQ's live request still tracks (its active work). */
  liveTaskIds: ReadonlySet<string>;
  /** Worktrees of the HQ's open fan-out tasks. */
  fanoutWorktrees: readonly string[];
  /** Root vetting; defaults to isAcceptableReadRoot. Injected in tests. */
  accept?: (root: string) => boolean;
}

/**
 * The roots to write. An open hand-off's root stands (re-stamped each
 * refresh); an ended one stays up to READ_ROOT_GRACE_MS after its end, and
 * only while Moa's live request still tracks its task: finishing the job,
 * the pane closing, or Moa going off removes it at once.
 */
export function computeReadRoots(src: ReadRootSources): ReadRoot[] {
  if (!src.enabled) return [];
  const best = new Map<string, number>();
  const add = (p: string, expiresAt: number): void => {
    if (expiresAt <= src.now) return;
    best.set(p, Math.max(best.get(p) ?? 0, expiresAt));
  };
  const accept = src.accept ?? ((p: string) => isAcceptableReadRoot(p));
  for (const h of src.handoffs) {
    if (!h.repoRoot || !accept(h.repoRoot)) continue;
    if (h.open) add(h.repoRoot, src.now + READ_ROOT_OPEN_TTL_MS);
    else if (!h.paneGone && h.endedAt !== undefined && h.taskId && src.liveTaskIds.has(h.taskId)) {
      add(h.repoRoot, h.endedAt + READ_ROOT_GRACE_MS);
    }
  }
  for (const w of src.fanoutWorktrees) if (accept(w)) add(w, src.now + READ_ROOT_OPEN_TTL_MS);
  return [...best.entries()].map(([p, expiresAt]) => ({ path: p, expiresAt })).sort((a, b) => a.path.localeCompare(b.path));
}

let refresher: (() => Promise<void>) | null = null;
/** deck.handler installs the refresh; deck.rpc calls it after a finished job. */
export function setMoaReadRootsRefresher(fn: (() => Promise<void>) | null): void {
  refresher = fn;
}
export function refreshMoaReadRoots(): Promise<void> {
  return refresher ? refresher().catch(() => undefined) : Promise.resolve();
}
