// English strings new to chat v2. Shared chat wording comes from the `chat.*`
// locale keys; these move into the locale files when the view leaves
// experimental.
export const S = {
  newChat: 'New chat',
  newChatHint: 'Starts Claude Code in this pane as a chat. The terminal stays as it is.',
  agent: 'Agent',
  model: 'Model',
  effort: 'Effort',
  effortDefault: 'Default effort',
  effortFixed: 'Effort is set by the agent for this chat.',
  permission: 'Permissions',
  modeDefault: 'Ask',
  modeBypass: 'Bypass',
  modeDefaultHint: 'The agent asks before gated tools run.',
  modeBypassHint: 'The agent runs every tool without asking.',
  modelFixed: 'Set when the chat started.',
  placeholder: 'Message Claude Code…',
  placeholderNew: 'What should Claude Code do?',
  placeholderHandedOff: 'This chat continues in Terminal.',
  send: 'Send',
  stop: 'Stop',
  continueInTerminal: 'Continue in Terminal',
  continueInTerminalHint: 'Stops the chat and resumes the same conversation in this terminal.',
  handedOff: 'This conversation moved to Terminal.',
  closeChat: 'Close chat',
  startNewChat: 'New chat',
  startNewChatHint: 'Closes this chat record. The conversation stays in the agent\u2019s history and in Terminal.',
  attachUnsupported: 'This chat does not take attachments.',
  attachImagesOnly: 'Only images can be attached.',
  attachRefused: 'An image could not be attached.',
  removeAttachment: 'Remove',
  showFullText: 'Show full text',
  loadingFull: 'Loading…',
  showRest: 'Show the rest',
  partialLoaded: 'Only part of the text loaded.',
  runsIn: (dir: string) => `Runs in ${dir}`,
  runsInUnknown: 'Runs in the shell\u2019s working directory, or where this pane started.',
  workingDirectory: 'Working directory',
  allow: 'Allow',
  deny: 'Deny',
  submit: 'Submit',
  skip: 'Skip',
  allowed: 'Allowed',
  denied: 'Denied',
  cancelled: 'Cancelled',
  answerOther: 'Other answer',
  approvalTitle: 'Permission needed',
  thinking: 'Thinking',
  working: 'Working',
  worked: 'worked',
  workedFor: 'worked for',
  interrupted: 'Interrupted',
  failed: 'Failed',
  usageLimited: 'Usage limit reached',
  showOutput: 'Output',
  showMore: 'Show full output',
  bodyGone: 'The full output is no longer kept.',
  openFile: 'Open file',
  subagent: 'Subagent',
  steps: (n: number) => (n === 1 ? '1 step' : `${n} steps`),
  groupRead: (n: number) => `Read ${n} files`,
  groupEdited: (n: number) => `Edited ${n} files`,
  groupRan: (n: number) => `Ran ${n} commands`,
  groupSearched: (n: number) => `Searched ${n} times`,
  groupMixed: (n: number) => `Ran ${n} tool calls`,
  find: 'Find in conversation',
  findPlaceholder: 'Find',
  findCount: (index: number, total: number) => (total ? `${index} of ${total}` : 'No results'),
  findNext: 'Next match',
  findPrev: 'Previous match',
  findClose: 'Close find',
  loadEarlier: 'Load earlier messages',
  status: {
    starting: 'Starting…',
    idle: 'Ready',
    running: 'Working',
    'needs-input': 'Waiting for you',
    stopped: 'Stopped · the next message resumes it',
    failed: 'Could not start',
    'handed-off': 'In Terminal',
  },
  unavailable: 'Chat is unavailable. Use Terminal, or try again.',
  retry: 'Retry',
  error: 'Something went wrong.',
} as const;
